server:
  port: ${PORT:8889}

spring:
  application:
    name: config-service
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: "file:./config-services-properties/{application}"
          # file:///${user.home}/workspace/microservices/config-services-properties/{application}/{profile}
          # classpath:/config # this is the default

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: error
    org.springframework: info
    com.melardev: debug



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
